# Generated by Django 4.2.6 on 2023-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre_cargo', models.CharField(max_length=255)),
                ('sueldo', models.FloatField()),
                ('experiencia', models.CharField(max_length=255)),
                ('tipo_contrato', models.CharField(max_length=255)),
                ('modalidad_trabajo', models.CharField(max_length=255)),
                ('localizacion', models.CharField(max_length=255)),
                ('n_vacantes', models.IntegerField()),
                ('postulaciones', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
